spring:
    config:
        activate:
            on-profile: prod
    r2dbc:
        url: r2dbc:postgresql://localhost:5432/test_database
        username: root
        password: root1234
    datasource-postgres:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/test_database
        username: root
        password: root1234
    jpa:
        hibernate:
            ddl-auto: none
            naming:
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
                physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        properties:
            hibernate:
                show_sql: false
                format_sql: false
                use_sql_comments: false
                hbm2ddl:
                    auto: validate
                dialect: org.hibernate.dialect.PostgreSQLDialect
        database: postgresql
    flyway:
        url: jdbc:postgresql://localhost:5432/test_database
        user: root
        password: root1234
        baseline-version: 0
        sql-migration-suffixes: ddl
        baseline-on-migrate: true
        validate-on-migrate: true
        locations: classpath:db/migration,classpath:db/migration/postgresql
    data:
        mongodb:
            database: test_database
            host: localhost
            username: root
            password: root1234
            port: 27017
            authentication-database: admin
server:
    port: 8080
logging:
    config: classpath:logback/logback-prod.xml