spring:
    config:
        activate:
            on-profile: local
    devtools:
        livereload:
            enabled: true
    r2dbc:
        url: r2dbc:postgresql://localhost:5432/test_database
        username: root
        password: root1234
        pool:
            initial-size: 100
            validation-query: SELECT 1
    datasource-postgres:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/test_database
        username: root
        password: root1234
    jpa:
        hibernate:
            ddl-auto: none
            naming:
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
                physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
                hbm2ddl:
                    auto: validate
                dialect: org.hibernate.dialect.PostgreSQLDialect
        database: postgresql
    flyway:
        url: jdbc:postgresql://localhost:5432/test_database
        user: root
        password: root1234
        baseline-version: 0
        sql-migration-suffixes: ddl
        baseline-on-migrate: true
        validate-on-migrate: true
        locations: classpath:db/migration,classpath:db/migration/postgresql
        enabled: true
    kafka:
        producer:
            bootstrap-servers: localhost:9092
        consumer:
            bootstrap-servers: localhost:9092
            auto-offset-reset: earliest
            group-id: tablo-kafka-group
            enable-auto-commit: true
        listener:
            ack-mode: manual
        bootstrap-servers: localhost:9092
server:
    port: 9090
logging:
    level:
        root: info
        org.hibernate.sql: debug
        org.hibernate.type.descriptor.sql: trace
        io.r2dbc.sql: TRACE