spring:
    config:
        activate:
            on-profile: local
    devtools:
        livereload:
            enabled: true
    datasource:
        hikari:
            maximum-pool-size: 4
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/test_database?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
        username: test_user
        password: test_user@password@1234
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
server:
    port: 9090