spring:
    config:
        activate:
            on-profile: dev
    devtools:
        livereload:
            enabled: true
    r2dbc:
        url: r2dbc:postgresql://localhost:5432/test_database
        username: root
        password: root1234
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/test_database
        username: root
        password: root1234
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
server:
    port: 9090