spring:
    config:
        activate:
            on-profile: local
    devtools:
        livereload:
            enabled: true
    redis:
        lettuce:
          pool:
              max-active: 10
              max-idle: 10
              min-idle: 2
        host: localhost
        port: 6379
        password: root1234
    r2dbc:
        url: r2dbc:postgresql://localhost:5432/test_database
        username: root
        password: root1234
        pool:
            initial-size: 100
            validation-query: SELECT 1
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/test_database
        username: root
        password: root1234
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    flyway:
        url: jdbc:postgresql://localhost:5432/test_database
        user: root
        password: root1234
        baseline-version: 0
        sql-migration-suffixes: ddl
        baseline-on-migrate: true
        validate-on-migrate: true
server:
    port: 9090
logging:
    level:
        root: info
        org.hibernate.sql: debug
        org.hibernate.type.descriptor.sql: trace
        io.r2dbc.sql: TRACE