# Use root/example as user/password credentials
version: '3.1'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "80:8080"
    volumes:
      - ../../build/doc:/usr/share/nginx/html/doc
    environment:
      SWAGGER_JSON: doc/oas-doc.yaml
      API_URL: doc/oas-doc.yaml