version: '3.1'

services:
  db:
    container_name: test_postgres
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_DB: test_database
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root1234
    ports:
      - "5432:5432"